networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.40.0.0/24

services:
  technitium-dns:
    container_name: technitium-dns
    hostname: technitium-dns
    networks:
      private_network:
        ipv4_address: 10.40.0.2
    image: technitium/dns-server:latest
    ports:
      - "8081:5380/tcp"
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp" #DNS-over-TLS service
      # - "443:443/udp" #DNS-over-HTTPS service (HTTP/3) USING THIS PORT FOR WIREGUARD
      - "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
    environment:
      - DNS_SERVER_DOMAIN=dns-server
      - DNS_SERVER_RECURSION_NETWORK_ACL=10.0.0.0/24,10.40.0.0/24,10.69.69.0/24
      - DNS_SERVER_ENABLE_BLOCKING=true
      - DNS_SERVER_BLOCK_LIST_URLS= https://big.oisd.nl/
    env_file:
      - /srv/envs/technitium.env

    volumes:
      - /srv/wirehole/technitium:/etc/dns
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    deploy:
      resources:
        limits:
          memory: 250M
    restart: unless-stopped

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - /srv/wirehole/wg-easy:/etc/wireguard
    networks:
      private_network:
        ipv4_address: 10.40.0.3
    ports:
      - "443:443/udp"
      - "8082:51821/tcp"
    dns:
      - 10.40.0.2 # Points to technitium
    environment:
      WG_PORT: 443
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 10.69.69.x
      WG_DEFAULT_DNS: 10.40.0.2
    env_file:
      - /srv/envs/wg-easy.env
    deploy:
      resources:
        limits:
          memory: 100M
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
